packages:
  - packages/*
  - packages/adapters/*
  - packages/plugins/*
  - packages/plugins/examples/*
  - server
  - ui
  - cli
allowBuilds:
  '@embedded-postgres/linux-x64': true
  '@embedded-postgres/windows-x64': true
  electron: true
  electron-winstaller: true
  es5-ext: true
  esbuild: true
